"""AvaxCats collection generator — Team Avalanche (Team1 VN).

  python3 generate.py --count 100 --seed 42 --out output
  python3 generate.py --count 24 --sheet          # + contact sheet for review
  python3 generate.py --catalog                   # render one card per trait

Outputs per token: images/<id>.png (upscaled), thumbs/<id>.png (native 32px),
metadata/<id>.json (OpenSea-style), plus collection.json with rarity stats.
"""

import argparse
import json
import os
import random

import engine
from engine import (contact_sheet, dilate, mask_of, new_grid, overlay,
                    save_grid)
from traits import (CATEGORIES, FURS, FUR_BY_NAME, SPECIAL_EYES,
                    draw_base_cat)

DESCRIPTION = ("AvaxCats — 32x32 pixel summit cats of Team Avalanche "
               "(Team1 VN). Born in the snow, bleeding AVAX red, riding "
               "candles down the mountain. Generated by the nullcat "
               "workflow.")


def pick(rng, traits):
    total = sum(t["w"] for t in traits)
    # ❓ Weighted random là gì — tại sao không dùng rng.choice?
    # → rng.choice chọn đều nhau; ở đây mỗi trait có trọng số w (common=100 … legendary=5).
    # → Bốc số r trong [0, tổng w] rồi cộng dồn: trait có w lớn chiếm đoạn dài hơn nên dễ trúng hơn.
    r = rng.uniform(0, total)
    acc = 0.0
    for t in traits:
        acc += t["w"]
        if r <= acc:
            return t
    return traits[-1]


def roll(rng):
    chosen = {}
    cats = dict(CATEGORIES)
    for cat_name, traits in CATEGORIES:
        chosen[cat_name] = pick(rng, traits)
    # ❓ Vì sao mắt đặc biệt thì bị bỏ kính?
    # → Fit-coherence: Laser/Diamond/Hypno… vẽ đè lên vùng mắt; thêm kính lên nữa sẽ che mất trait hiếm.
    # → Nên ép Eyewear về "None" — mắt hiếm luôn thắng, ảnh và metadata khớp nhau.
    if chosen["Eyes"]["name"] in SPECIAL_EYES and chosen["Eyewear"]["name"] != "None":
        chosen["Eyewear"] = next(t for t in cats["Eyewear"] if t["name"] == "None")
    # ❓ Còn VR Headset thì ngược lại — ép mắt về Normal?
    # → VR Headset che kín toàn bộ vùng mắt nên mọi mắt đặc biệt đều vô hình.
    # → Reset về Normal để metadata không "khoe" một trait hiếm mà ảnh không hề hiển thị.
    if chosen["Eyewear"]["name"] == "VR Headset":
        chosen["Eyes"] = next(t for t in cats["Eyes"] if t["name"] == "Normal")


    # ❓ Tại sao Hood lại xoá Mane?
    # → Hood trùm kín từ đỉnh đầu xuống cổ, còn Mane (bờm, râu quai nón) vẽ đúng vùng đó.
    # → Để cả hai thì bờm lòi ra ngoài vành hood trông lỗi; quy tắc này giữ ảnh và metadata nhất quán.
    if chosen["Headwear"]["name"] == "The Avalanche Hood":
        chosen["Mane"] = next(t for t in cats["Mane"] if t["name"] == "None")
    return chosen


# ❓ Thứ tự trong PART_ORDER có quan trọng không?
# → Rất quan trọng: layer vẽ sau đè lên layer vẽ trước. Belly/Pattern sát thân, Outfit đè lên,
# → rồi mắt/miệng, kính đè lên mắt, mũ đè lên tất cả. Đổi thứ tự là kính sẽ bị mắt che.
PART_ORDER = ["Belly", "Pattern", "Tail", "Mane", "Outfit", "Whiskers",
              "Eyes", "Mouth", "Earring", "Eyewear", "Headwear", "Paw Item"]


# ❓ CLIP_EXACT và CLIP_LOOSE khác nhau chỗ nào?
# → Belly/Pattern là lông nên phải cắt đúng theo silhouette thân (mask exact).
# → Outfit (áo, khăn) được phép chờm ra ngoài thân vài pixel (loose) — dùng mask đã dilate 3 lần.
CLIP_EXACT = {"Belly", "Pattern"}
CLIP_LOOSE = {"Outfit"}


def clip_to(g, mask):
    for y in range(engine.SIZE):
        for x in range(engine.SIZE):
            if not mask[y][x]:
                g[y][x] = None


def render(chosen, rng):
    # ❓ Vì sao cần 3 grid bg / cat / fg thay vì vẽ thẳng lên một ảnh?
    # → Ba layer: nền, thân mèo, hiệu ứng trước mặt (tia laser, mưa coin). Tách ra để lấy mask
    # → của riêng thân mèo (clipping) và để hiệu ứng luôn đè lên mèo dù được vẽ từ trait Eyes.
    bg, cat, fg = new_grid(), new_grid(), new_grid()
    fur = FUR_BY_NAME[chosen["Fur"]["name"]]
    ctx = {"bg": bg, "cat": cat, "fg": fg, "fur": fur, "rng": rng}

    chosen["Background"]["fn"](ctx)
    draw_base_cat(ctx, chosen["Body"]["fn"], chosen["Ears"]["fn"],
                  chosen["Head"]["fn"])


    # ❓ Tại sao phải lấy body_mask ngay sau draw_base_cat?
    # → Lúc này grid cat chỉ có thân + đầu + tai, nên mask chính là silhouette mèo "trần".
    # → Lấy muộn hơn thì mũ/áo đã dính vào mask và clipping mất tác dụng.
    # → Trait cần clip sẽ vẽ "thô" lên grid tạm tmp, clip_to cắt theo mask, rồi mới overlay vào cat.
    body_mask = mask_of(cat)
    loose_mask = dilate(dilate(dilate(body_mask)))

    for part in PART_ORDER:
        t = chosen[part]
        if t["fn"] is None:
            continue
        if part in CLIP_EXACT or part in CLIP_LOOSE:
            tmp = new_grid()
            ctx["cat"] = tmp
            t["fn"](ctx)
            ctx["cat"] = cat
            clip_to(tmp, body_mask if part in CLIP_EXACT else loose_mask)
            overlay(cat, tmp)
        else:
            t["fn"](ctx)
    fx = chosen["Effect"]
    if fx["fn"] is not None:
        fx["fn"](ctx)

    out = new_grid()
    overlay(out, bg)
    overlay(out, cat)
    overlay(out, fg)
    return out


def rarity_score(chosen):
    score = 0.0
    cats = dict(CATEGORIES)
    for cat_name, t in chosen.items():
        total = sum(x["w"] for x in cats[cat_name])
        # ❓ Điểm rarity tính thế nào?
        # → Mỗi trait góp tổng_w / w — trait càng hiếm (w nhỏ) điểm càng cao. Cộng dồn 18 category
        # → ra một số để xếp hạng mèo hiếm nhất trong batch (preview dùng làm hero).
        score += total / t["w"]
    return round(score, 2)


def token_metadata(idx, chosen):
    # ❓ Định dạng metadata này ai quy định?
    # → Chuẩn OpenSea / ERC-721 metadata: name, description, image và attributes = list {trait_type, value}.
    # → Marketplace đọc đúng các key này để hiển thị trait; khối "rarity" là phần mở rộng riêng của dự án.
    return {
        "name": f"AvaxCat #{idx:04d}",
        "description": DESCRIPTION,
        "image": f"images/{idx:04d}.png",
        "attributes": [
            {"trait_type": cat, "value": t["name"]}
            for cat, t in chosen.items()
        ],
        "rarity": {
            "score": rarity_score(chosen),
            "tiers": {cat: t["tier"] for cat, t in chosen.items()},
        },
    }


def generate(count, seed, outdir, scale, sheet):
    for sub in ("images", "thumbs", "metadata"):
        os.makedirs(os.path.join(outdir, sub), exist_ok=True)

    # ❓ Fixed seed để làm gì?
    # → Cùng seed → cùng chuỗi số ngẫu nhiên → cùng 48 con mèo y hệt trên mọi máy (reproducibility).
    # → master chỉ phát seed con; mỗi token có RNG riêng nên có thể tái tạo 1 con từ token_seed trong metadata.
    master = random.Random(seed)
    seen = set()
    tokens = []
    grids = []
    i = 0
    attempts = 0
    while i < count and attempts < count * 60:
        attempts += 1
        token_seed = master.randrange(2 ** 31)
        rng = random.Random(token_seed)
        chosen = roll(rng)
        # ❓ Làm sao đảm bảo không có 2 mèo giống hệt nhau?
        # → key = tuple tên trait của 18 category. Nếu đã gặp thì bỏ qua và roll lại (continue, không tăng i).
        # → attempts < count*60 chặn vòng lặp vô hạn khi số tổ hợp khả dĩ ít hơn count.
        key = tuple(t["name"] for t in chosen.values())
        if key in seen:
            continue
        seen.add(key)
        g = render(chosen, rng)
        save_grid(os.path.join(outdir, "images", f"{i:04d}.png"), g, scale=scale)
        save_grid(os.path.join(outdir, "thumbs", f"{i:04d}.png"), g, scale=1)
        meta = token_metadata(i, chosen)
        meta["seed"] = token_seed
        with open(os.path.join(outdir, "metadata", f"{i:04d}.json"), "w") as f:
            json.dump(meta, f, indent=2)
        tokens.append(meta)
        grids.append(g)
        i += 1


    counts = {}
    for t in tokens:
        for a in t["attributes"]:
            counts.setdefault(a["trait_type"], {}).setdefault(a["value"], 0)
            counts[a["trait_type"]][a["value"]] += 1
    with open(os.path.join(outdir, "collection.json"), "w") as f:
        json.dump({"name": "AvaxCats — Team Avalanche (Team1 VN)",
                   "count": len(tokens), "seed": seed,
                   "trait_counts": counts}, f, indent=2)

    if sheet:
        cols = 8 if count >= 32 else 6
        contact_sheet(os.path.join(outdir, "sheet.png"), grids, cols=cols, scale=6)
    print(f"generated {len(tokens)} tokens -> {outdir}")


def catalog(outdir, scale):
    """One card per trait, rendered on a neutral base cat."""
    os.makedirs(outdir, exist_ok=True)
    cats = dict(CATEGORIES)
    base = {cat: next(t for t in ts if t["name"] in
                      ("Frost", "Orange Tabby", "Sitting", "Pointy", "Classic",
                       "Plain", "Normal", "Smile", "Short", "None"))
            for cat, ts in CATEGORIES}
    index = {}
    grids = []
    for cat_name, ts in CATEGORIES:
        index[cat_name] = []
        for t in ts:
            chosen = dict(base)
            chosen[cat_name] = t
            if cat_name == "Fur":
                pass
            rng = random.Random(hash((cat_name, t["name"])) & 0xFFFFFFF)
            g = render(chosen, rng)
            fname = f"{cat_name}_{t['name']}".replace(" ", "_").replace("&", "and")
            fname = "".join(ch for ch in fname if ch.isalnum() or ch in "_-") + ".png"
            save_grid(os.path.join(outdir, fname), g, scale=scale)
            index[cat_name].append({"name": t["name"], "tier": t["tier"], "file": fname})
            grids.append(g)
    with open(os.path.join(outdir, "catalog.json"), "w") as f:
        json.dump(index, f, indent=2)
    contact_sheet(os.path.join(outdir, "catalog_sheet.png"), grids, cols=10, scale=5)
    total = sum(len(v) for v in index.values())
    print(f"catalog: {total} traits -> {outdir}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=24)
    ap.add_argument("--seed", type=int, default=1337)
    ap.add_argument("--out", default="output")
    ap.add_argument("--scale", type=int, default=16)
    ap.add_argument("--sheet", action="store_true")
    ap.add_argument("--catalog", action="store_true")
    args = ap.parse_args()

    if args.catalog:
        catalog(os.path.join(args.out, "catalog"), scale=1)
    else:
        generate(args.count, args.seed, args.out, args.scale, args.sheet)


if __name__ == "__main__":
    main()
