"""AvaxCats collection generator — Team Avalanche (Team1 VN).

  python3 generate.py --count 100 --seed 42 --out output
  python3 generate.py --count 24 --sheet          # + contact sheet for review
  python3 generate.py --catalog                   # render one card per trait

Outputs per token: images/<id>.png (upscaled), thumbs/<id>.png (native 32px),
metadata/<id>.json (OpenSea-style), plus collection.json with rarity stats.
"""

import argparse
import json
import os
import random

import engine
from engine import (contact_sheet, dilate, mask_of, new_grid, overlay,
                    save_grid)
from traits import (CATEGORIES, FURS, FUR_BY_NAME, SPECIAL_EYES,
                    draw_base_cat)

DESCRIPTION = ("AvaxCats — 32x32 pixel summit cats of Team Avalanche "
               "(Team1 VN). Born in the snow, bleeding AVAX red, riding "
               "candles down the mountain. Generated by the nullcat "
               "workflow.")


def pick(rng, traits):
    total = sum(t["w"] for t in traits)
    r = rng.uniform(0, total)
    acc = 0.0
    for t in traits:
        acc += t["w"]
        if r <= acc:
            return t
    return traits[-1]


def roll(rng):
    chosen = {}
    cats = dict(CATEGORIES)
    for cat_name, traits in CATEGORIES:
        chosen[cat_name] = pick(rng, traits)
    if chosen["Eyes"]["name"] in SPECIAL_EYES and chosen["Eyewear"]["name"] != "None":
        chosen["Eyewear"] = next(t for t in cats["Eyewear"] if t["name"] == "None")
    if chosen["Eyewear"]["name"] == "VR Headset":
        chosen["Eyes"] = next(t for t in cats["Eyes"] if t["name"] == "Normal")


    if chosen["Headwear"]["name"] == "The Avalanche Hood":
        chosen["Mane"] = next(t for t in cats["Mane"] if t["name"] == "None")
    return chosen


PART_ORDER = ["Belly", "Pattern", "Tail", "Mane", "Outfit", "Whiskers",
              "Eyes", "Mouth", "Earring", "Eyewear", "Headwear", "Paw Item"]


CLIP_EXACT = {"Belly", "Pattern"}
CLIP_LOOSE = {"Outfit"}


def clip_to(g, mask):
    for y in range(engine.SIZE):
        for x in range(engine.SIZE):
            if not mask[y][x]:
                g[y][x] = None


def render(chosen, rng):
    bg, cat, fg = new_grid(), new_grid(), new_grid()
    fur = FUR_BY_NAME[chosen["Fur"]["name"]]
    ctx = {"bg": bg, "cat": cat, "fg": fg, "fur": fur, "rng": rng}

    chosen["Background"]["fn"](ctx)
    draw_base_cat(ctx, chosen["Body"]["fn"], chosen["Ears"]["fn"],
                  chosen["Head"]["fn"])


    body_mask = mask_of(cat)
    loose_mask = dilate(dilate(dilate(body_mask)))

    for part in PART_ORDER:
        t = chosen[part]
        if t["fn"] is None:
            continue
        if part in CLIP_EXACT or part in CLIP_LOOSE:
            tmp = new_grid()
            ctx["cat"] = tmp
            t["fn"](ctx)
            ctx["cat"] = cat
            clip_to(tmp, body_mask if part in CLIP_EXACT else loose_mask)
            overlay(cat, tmp)
        else:
            t["fn"](ctx)
    fx = chosen["Effect"]
    if fx["fn"] is not None:
        fx["fn"](ctx)

    out = new_grid()
    overlay(out, bg)
    overlay(out, cat)
    overlay(out, fg)
    return out


def rarity_score(chosen):
    score = 0.0
    cats = dict(CATEGORIES)
    for cat_name, t in chosen.items():
        total = sum(x["w"] for x in cats[cat_name])
        score += total / t["w"]
    return round(score, 2)


def token_metadata(idx, chosen):
    return {
        "name": f"AvaxCat #{idx:04d}",
        "description": DESCRIPTION,
        "image": f"images/{idx:04d}.png",
        "attributes": [
            {"trait_type": cat, "value": t["name"]}
            for cat, t in chosen.items()
        ],
        "rarity": {
            "score": rarity_score(chosen),
            "tiers": {cat: t["tier"] for cat, t in chosen.items()},
        },
    }


def generate(count, seed, outdir, scale, sheet):
    for sub in ("images", "thumbs", "metadata"):
        os.makedirs(os.path.join(outdir, sub), exist_ok=True)

    master = random.Random(seed)
    seen = set()
    tokens = []
    grids = []
    i = 0
    attempts = 0
    while i < count and attempts < count * 60:
        attempts += 1
        token_seed = master.randrange(2 ** 31)
        rng = random.Random(token_seed)
        chosen = roll(rng)
        key = tuple(t["name"] for t in chosen.values())
        if key in seen:
            continue
        seen.add(key)
        g = render(chosen, rng)
        save_grid(os.path.join(outdir, "images", f"{i:04d}.png"), g, scale=scale)
        save_grid(os.path.join(outdir, "thumbs", f"{i:04d}.png"), g, scale=1)
        meta = token_metadata(i, chosen)
        meta["seed"] = token_seed
        with open(os.path.join(outdir, "metadata", f"{i:04d}.json"), "w") as f:
            json.dump(meta, f, indent=2)
        tokens.append(meta)
        grids.append(g)
        i += 1


    counts = {}
    for t in tokens:
        for a in t["attributes"]:
            counts.setdefault(a["trait_type"], {}).setdefault(a["value"], 0)
            counts[a["trait_type"]][a["value"]] += 1
    with open(os.path.join(outdir, "collection.json"), "w") as f:
        json.dump({"name": "AvaxCats — Team Avalanche (Team1 VN)",
                   "count": len(tokens), "seed": seed,
                   "trait_counts": counts}, f, indent=2)

    if sheet:
        cols = 8 if count >= 32 else 6
        contact_sheet(os.path.join(outdir, "sheet.png"), grids, cols=cols, scale=6)
    print(f"generated {len(tokens)} tokens -> {outdir}")


def catalog(outdir, scale):
    """One card per trait, rendered on a neutral base cat."""
    os.makedirs(outdir, exist_ok=True)
    cats = dict(CATEGORIES)
    base = {cat: next(t for t in ts if t["name"] in
                      ("Frost", "Orange Tabby", "Sitting", "Pointy", "Classic",
                       "Plain", "Normal", "Smile", "Short", "None"))
            for cat, ts in CATEGORIES}
    index = {}
    grids = []
    for cat_name, ts in CATEGORIES:
        index[cat_name] = []
        for t in ts:
            chosen = dict(base)
            chosen[cat_name] = t
            if cat_name == "Fur":
                pass
            rng = random.Random(hash((cat_name, t["name"])) & 0xFFFFFFF)
            g = render(chosen, rng)
            fname = f"{cat_name}_{t['name']}".replace(" ", "_").replace("&", "and")
            fname = "".join(ch for ch in fname if ch.isalnum() or ch in "_-") + ".png"
            save_grid(os.path.join(outdir, fname), g, scale=scale)
            index[cat_name].append({"name": t["name"], "tier": t["tier"], "file": fname})
            grids.append(g)
    with open(os.path.join(outdir, "catalog.json"), "w") as f:
        json.dump(index, f, indent=2)
    contact_sheet(os.path.join(outdir, "catalog_sheet.png"), grids, cols=10, scale=5)
    total = sum(len(v) for v in index.values())
    print(f"catalog: {total} traits -> {outdir}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=24)
    ap.add_argument("--seed", type=int, default=1337)
    ap.add_argument("--out", default="output")
    ap.add_argument("--scale", type=int, default=16)
    ap.add_argument("--sheet", action="store_true")
    ap.add_argument("--catalog", action="store_true")
    args = ap.parse_args()

    if args.catalog:
        catalog(os.path.join(args.out, "catalog"), scale=1)
    else:
        generate(args.count, args.seed, args.out, args.scale, args.sheet)


if __name__ == "__main__":
    main()
